# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 484c60b6a5eab0c4d03b026892a8f504961392f2dc914ba6a58f31555a5deb7f627efadecfc58ae6594b364b4687ae4abc9fcfed4cfbfa276e1b3642750f153d

test:
  secret_key_base: 8fbd18541bc2d56a047668b141d7f3e89ea307371eae3ccde10c79bc14cdfb756c200f86ece77c42a48e5b27cdf389d30d0ff3e45e020dec559bf69b8062140b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
